### ISSUE TITLE
Convert all samples to use the Defang GH action from marketplace

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/samples#172]
```
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.0.4
```
